# Generated by Django 3.2.7 on 2021-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_en', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_fr', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_de', models.CharField(blank=True, max_length=1024, null=True)),
                ('language', models.CharField(max_length=16)),
            ],
        ),
    ]
