# Generated by Django 3.2.7 on 2021-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilang_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimodel',
            name='content_en',
        ),
        migrations.AlterField(
            model_name='multimodel',
            name='content',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='multimodel',
            name='content_de',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='multimodel',
            name='content_fr',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
